services:
  ai-reception:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: ai-reception
    restart: unless-stopped
    ports:
      # By default bind to localhost so the backend is only reachable from
      # the host (safer when using nginx as the reverse proxy). You can
      # override the bind address at runtime by exporting BIND_HOST.
      # Example to publish to all interfaces:
      #   BIND_HOST=0.0.0.0 sudo docker compose up -d --build
      - "${BIND_HOST:-127.0.0.1}:5040:5040"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata/
      - FASTAPI_ENV=production
      # Optional override to bind backend to localhost only. If set to
      # 127.0.0.1 the container's port will still be published, but the
      # intention is to document how to run; controlling host bind requires
      # `docker run -p 127.0.0.1:5040:5040 ...` or using a compose override.
      # UVICORN_HOST is read by the startup command if you wire it in the
      # Dockerfile/CMD; keep it here for documentation.
      - UVICORN_HOST=0.0.0.0
      # Tunable number of uvicorn workers (set at deployment time). If unset, Dockerfile default will be used.
      - UVICORN_WORKERS=4
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5040/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
