services:
  ai-reception:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: ai-reception
    restart: unless-stopped
    ports:
      # bind to localhost so only the host (nginx) can access it
      - "127.0.0.1:5040:5040"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata/
      - FASTAPI_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5040/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
